# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QTextEdit, QFileDialog

from src.sorter import Sorter
import re

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(550, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.insert = QtWidgets.QWidget()
        self.insert.setObjectName("insert")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.insert)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 521, 691))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.tabWidget.addTab(self.insert, "")
        self.shell = QtWidgets.QWidget()
        self.shell.setObjectName("shell")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.shell)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, 521, 691))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.textEdit_3 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.verticalLayout_3.addWidget(self.textEdit_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_3.addWidget(self.pushButton_4)
        self.textEdit_4 = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit_4.setReadOnly(True)
        self.textEdit_4.setObjectName("textEdit_4")
        self.verticalLayout_3.addWidget(self.textEdit_4)
        self.tabWidget.addTab(self.shell, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Выбрать файл"))
        self.label.setText(_translate("MainWindow", "Введите массив вручную"))
        self.pushButton_3.setText(_translate("MainWindow", "Подтвердить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.insert), _translate("MainWindow", "Insert Sort"))
        self.pushButton_2.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_2.setText(_translate("MainWindow", "Введите массив вручную"))
        self.pushButton_4.setText(_translate("MainWindow", "Подтвердить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shell), _translate("MainWindow", "Shell Sort"))
        self.pushButton.clicked.connect(self.file_open)
        self.pushButton_2.clicked.connect(self.file_open2)
        self.pushButton_3.clicked.connect(self.read)
        self.pushButton_4.clicked.connect(self.read2)

    def file_open(self):
        filename = QFileDialog.getOpenFileName()
        path = filename[0]
        sorter = Sorter()
        unsortedArray = sorter.readArrayFromFile(path)
        insertSortedArrayWithIndex = sorter.insertionSort(unsortedArray)
        counter = insertSortedArrayWithIndex[len(insertSortedArrayWithIndex) - 1]
        insertSortedArray = insertSortedArrayWithIndex[:-1]
        for i in insertSortedArray:
            self.textEdit.append(str(i))
        self.textEdit.append("Количество шагов: ")
        self.textEdit.append(str(counter))

    def file_open2(self):
        filename = QFileDialog.getOpenFileName()
        path = filename[0]
        sorter = Sorter()
        unsortedArray = sorter.readArrayFromFile(path)
        shellSortedArrayWithIndex = sorter.shellSort(unsortedArray)
        counter = shellSortedArrayWithIndex[len(shellSortedArrayWithIndex) - 1]
        shellSortedArray = shellSortedArrayWithIndex[:-1]
        for i in shellSortedArray:
            self.textEdit_3.append(str(i))
        self.textEdit_3.append("Количество шагов: ")
        self.textEdit_3.append(str(counter))

    def read(self):
        sorter = Sorter()
        text = self.lineEdit.text()
        list = re.findall('\d+', text)
        list = [int(numeric_string) for numeric_string in list]
        list = sorter.insertionSort(list)
        counter = list[len(list) - 1]
        list = list[:-1]
        self.textEdit_2.append(str(list))
        self.textEdit_2.append("Количество шагов: ")
        self.textEdit_2.append(str(counter))

    def read2(self):
        sorter = Sorter()
        text = self.lineEdit_2.text()
        list = re.findall('\d+', text)
        list = [int(numeric_string) for numeric_string in list]
        list = sorter.shellSort(list)
        counter = list[len(list) - 1]
        list = list[:-1]
        self.textEdit_4.append(str(list))
        self.textEdit_4.append("Количество шагов: ")
        self.textEdit_4.append(str(counter))

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
